// <auto-generated />
namespace MallRoof.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mall_user_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mall_user_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201910071048508_mall_user_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
