// <auto-generated />
namespace MallRoof.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mall_has_required_user_____Photo_premises : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mall_has_required_user_____Photo_premises));
        
        string IMigrationMetadata.Id
        {
            get { return "201912140932179_mall_has_required_user_____Photo_premises"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
