// <auto-generated />
namespace MallRoof.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_mall_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_mall_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201909260634189_user_mall_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
