// <auto-generated />
namespace MallRoof.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nothing_before_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nothing_before_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121016571_nothing_before_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
