// <auto-generated />
namespace MallRoof.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class proposal2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proposal2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006180804228_proposal2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
